#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
PROFILE=${1:-}
if [[ "$PROFILE" != "laptop" && "$PROFILE" != "server" ]]; then
  echo "usage: $0 laptop|server init|preflight|<docker compose arguments...>" >&2
  exit 64
fi
shift
if (($# == 0)); then
  echo "usage: $0 laptop|server init|preflight|<docker compose arguments...>" >&2
  exit 64
fi

case "$PROFILE" in
  laptop) OVERLAY="$ROOT/infra/docker-compose.laptop.yml" ;;
  server) OVERLAY="$ROOT/infra/docker-compose.server.yml" ;;
esac

ENV_FILE=${INSPECTOR_ENV_FILE:-$ROOT/infra/.env.$PROFILE}

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c "import secrets; print(secrets.token_hex($1))"
  else
    echo "openssl or python3 is required to generate deployment secrets" >&2
    exit 69
  fi
}

ensure_env() {
  [[ -f "$ENV_FILE" ]] && return
  local example="$ROOT/infra/$PROFILE.env.example"
  local temporary="$ENV_FILE.tmp.$$"
  local postgres_password rabbitmq_password redis_password minio_password worker_token
  postgres_password=$(random_hex 24)
  rabbitmq_password=$(random_hex 24)
  redis_password=$(random_hex 24)
  minio_password=$(random_hex 24)
  worker_token=$(random_hex 32)
  umask 077
  {
    echo "# Generated by infra/stack.sh for the $PROFILE profile. Keep this file secret."
    echo "POSTGRES_PASSWORD=$postgres_password"
    echo "RABBITMQ_PASSWORD=$rabbitmq_password"
    echo "REDIS_PASSWORD=$redis_password"
    echo "MINIO_ROOT_PASSWORD=$minio_password"
    echo "INTERNAL_WORKER_TOKEN=$worker_token"
    while IFS= read -r line || [[ -n "$line" ]]; do
      case "$line" in
        POSTGRES_PASSWORD=*|RABBITMQ_PASSWORD=*|REDIS_PASSWORD=*|MINIO_ROOT_PASSWORD=*|INTERNAL_WORKER_TOKEN=*) ;;
        *) echo "$line" ;;
      esac
    done < "$example"
  } > "$temporary"
  chmod 0600 "$temporary"
  mv "$temporary" "$ENV_FILE"
  echo "Created $ENV_FILE with random local credentials." >&2
}

ensure_env
if [[ "$1" == "init" ]]; then
  echo "$ENV_FILE"
  exit 0
fi
gpu_device=$(awk -F= '$1 == "SERVER_GPU_DEVICE" || $1 == "LAPTOP_GPU_DEVICE" {print $2; exit}' "$ENV_FILE")
if [[ "$1" == "preflight" ]]; then
  INSPECTOR_PREFLIGHT_GPU_DEVICE=${gpu_device:-0} "$ROOT/infra/preflight.sh" "$PROFILE" "$ROOT"
  exit 0
fi
if [[ "$1" == "up" ]]; then
  INSPECTOR_PREFLIGHT_GPU_DEVICE=${gpu_device:-0} "$ROOT/infra/preflight.sh" "$PROFILE" "$ROOT"
fi

exec docker compose \
  --env-file "$ENV_FILE" \
  --project-name "inspector-ai-$PROFILE" \
  -f "$ROOT/infra/docker-compose.yml" \
  -f "$OVERLAY" \
  --profile "$PROFILE" \
  "$@"
