import assert from "node:assert/strict";
import { brotliDecompressSync } from "node:zlib";
import { test } from "vitest";
import { canonicalJson, sha256 } from "../src/canonical-json.js";
import { verifyLayerAssemblyProposals,
  type LayerAssemblyVerificationInput } from "../src/layer-assembly-proposals.js";

// Deterministic synthetic fixture generated by Python worker. No project source.
const workerFixtureBrotliBase64 = "G8V+owMxOA8tRH74SyHUsniH3NicFSvCni8OZidkP6qsEtxXlcMe9XgrIxdV5qd8XHHLS8nIxsuyAxsjJJn19z/8peoh/8EFLvBC16Ttb8caIWZ9aH+mfn0K8cQv7w1Mbpa+Lqmpw9K3/dEbebl/JscJUi7XkrwEaIFgicqT9DCZiXxqWimg7YF24JygNs7q/89pb0n/je1POgIBVKs0faU0wgLI+knP+qu03uyV1s5uWr1WADxAOkIdHcBhh2DbzAGq65px0lEIgBn7/HXyDd8jluph5Y+x+p7/vJtSIyW7gJjdJT/S3/Z4vH+aFgoenXgvyfFpLUmIcKZ9QjLmVp7PXUoysZn4kSyAZyYWWtQR2euRfZmCmztSVsNPuVpvUPbankLa3A20M0S1fkWKq5zq2G8b1r/muysUkDkSCZAFCCmFQ8G+UpGLI4d6gLskvppU+distm5CyrXqX3XEvMjiAcNCt/lihbOG9cVboHOYY7wXZdbhX23uaSQXKAUMYz4JTWplaRXULmQ/GmYba9AFbEteLGAJcyAQSdTM4xoDS88Pa1is3B+9eBw4RLMZWQmLlIUF0LH3tSfF47MJoayqqU2EFB+1Q1uUjm1Y+P8W1TNwqwudTOryZjnZns8/035sQcFCWion4iaW94t/pNpJBoFxnXK/Vg+ZIjX/2b+5BLtF3JXH3ujGHkaP3q0hOuHra1ArFIRWZjdkkhVutSyARzMW6yK2Z8+D55MvgpHPUNWW14ebNDSmLrqef/S4Orm5P3t5uQdepl8qJLJP+Gv/cT98HlhrK3YXhDE7o1RVJ83fSq4jOrlmRfiOcEvGMtoF9jRUY/6D+/lpFkCgizu8XqreVVnpXqXW2dvtmo53mG7iqTlP/Zp53mc8Ts4IWFiYiuwAL/cJcSbCfV8hNSOn3MWdFZJXQUzP5ymFUTiUrcVHv4s/GOz8w0oTr4RiRrKgyS/pHxxDRg7FHLWRHsWxPzCSk4wFlzToU3l4NFR6dKcckQ9asR+V3Bx2NxX8dcfPiu4CbG4EEn1Q6f/oOjMmcBfbakodE+sydYiNu/bwnljObFq1uHUU9HvzOAQPYmfVgJf9Cs6AxvPfdzUk/sG3dcueyFqw1IOthk7UuZ2nINyrI23VnCMdFRaL1wmZA/g0zJLre4EZaj39PX8TqZihvd0PgtpY7pOsKpgT/rdHLa1w2Oix4GxLfEGQ++7iTuaV0KPVB5LjcSEThyomJxp0Zkp9lZAv9IJ0naJN7JCaU4GkZBSwOjByMVisCpK1TwXmhoO5kxWg1YJ/8wbzKxM+a0SlsuUGZ7/sXnCYBtEyP6KQys0siMIxrM3m1Xpj1d35CB9Hiws07ZyGPTmU8Nz4kAVV5vRdqXEkGHhNVLTc1C0bQkSvXgzbtD5liuNMceNJ9yyynkBWXnlpT27mniM+nPM/dvpnHt1JOpVZ3//+EEysjztm2DtXc89KcGSoeVgVpQuD6K0+7nEhXNTxw/eUQDotqNbyDwo5ETjFcdbwrmrwMu+sDsrTW9+0NxdioD3HG7V5+oILc9PV8vLhJ0THFuQHlUxUB867onAnW0nNBkmnBdVb7jnTI1Z5JplaE1uIPujJ8bRo+Wm/LAZ+dpOoGniz2k/9Fd4g33x0J+m/DULu/ZR5kgSFna4ygzN35OnBOVrMPljgAUzhx9zHTnvv8cXMopy99qzosLKFwwCNqIYv5fYVJtVDB6X1quTmGqR0oKEzdGNnf6tlyKBGpi3k3rdKoZJtcTlbASB6UWPKVdu3RE1jRiWu7IjxQG2H2UM7FuX8tes8y0GUwM41iDYop+goyFjg6eeUNCtq0ySAvsqBWIWO6ytLSeM4ZFpD4cxEsIRZVoIsD7ewKaGVcVPjBVEJaTcvNIbj6UJWk+MJHFZMZgBvYLZVFM18xJzNuBbmxKkuvQ6+E0+IYFD7qRK7XR/ZHU2ThR3ilIMp4hVn3IGCmaWk1o+GnAeb9zJwLwN8T32ha7i7bFtvwEhPKewtYxaBofCoL7WI+8KbmeDI5k7ZYLvpJrInHGbw+Fly87xeJoDH/PBWzWMbY7EOJFE50yYKZ1bjtRdFSaPP0R/berYkNDZ46U4yAzM155G/LH3tyEynN2AKuIWZFlC0s2F2WCaiecTVIqSaMXUh9FOBbYYR5uQnkTIulBk5ZUEJMmiZbTMUzWydhc/LX1cBvobHcJjoO0lgljYHxqd9zA2QzzXlcq0lHxgCj/hSaxCKbvZYgsdv7o3E7lQfw2ham0ZNiaDyO0EABg/bame/CNyJt9mSSeGlvtSCQ+HMya9j9sznqGHQ/XDFQ58eVixXwVGyeimAT0u5p8dopnuAKeOVZ9u6Lbg5i7GsujTVVoz5YnDotfObKYqZGgQMGJykfOcUnEcCu81YponXnGkjFN1cPFdgGq1P4IhP/SYDnMI3wJQ63luHfEutJZkDxVYHqbQ3AUPj0V9u4a95u4U2Yku7Ejo6H+68hjdULnoR4/QgjVdnZBNsy4AubynVYJAYsT2W8RKn7nwkhFSyLCOEk3iG036ei+sySUNCjOrFVopEeBrWc3AW03NwGtR/euIlJkRcI9yX5dIfERxjfzxVSabxboYeC9pyd5DxNBhdYD+kyagMxyg0AWx/MDDbPbpIEeEIfRfannEKUC61H/t4eLjdO6VikM4E4pngMCppHe0DwL4yrhTxaxQwI/HHuqdsxA5l9lnOwRjRehSE6Rh8KNLW7C/3UQdHnPBeNK3n2ivjWq/swBEd8zIit007kJwKbVe8BVPJxGvceepFyb3kwfOgjoduT6/bzBt5WnO5sWHhw8BsYc308EVQbSDIoFDBPZqZDO6BddF3Jz9/nIAHOwAnl4y52onoYCjweS/vroc9UPRpZjWKRl+px3URvly4cqdAsHpeAKPqg37OBmASeUmPFghZxCHgFaJlz+Nzbz9HghADfmQsbJO4BvNcpPZNvGXuZ4m3hakcQRMjZFM4LchWjXJsn9916pXL47E9K1ahtKV8o6hFCyCCb5VZI+fteOi2LB2/OuTexqyo2WpBFgBeCGSuWi6ypnZPp8k2mb4u8nqnfGKt8Z4mHi1ESDDkTmKno2ZPQEHQ4ZqCbWtjbBHJ9MlRVlV5TdOkXEMS98oaCe5ITaTobPw1qx1pM9y5zD3jAUuUY2JqlMyVv/KrCRKSxMI08pqo1nJb+3D3LDSpQ22/vXLjPncmM3oUG9RFEcBHToNt84xfHSRucLhzKGX70FWk0oyqD739gsEM1nqAb2oJSuupJrL1Phd8aJIszEI5C9Y9DoVdRQniOvGaSsgdeuADTi07PSY8Dr5NgYF7qFpyla3TjUKQOFAJ5freLIYQ0l/J/SctB3mCBFAHpXGj/O2vFwe57J32Rii7iHPn7h65q0Si6vjrytyT6DimaYmDl+kOKPBcJIOzqz+SqG/VIggtM8CcQJh/VUeIQ5//kYU+9yO+fNUHQMaTrm4w7QNIyqhHIeqGWFTrAj7jtSWsIaLdYajDzlVXVxdZTCMBbuswPLZcyGBbOFz6zkVQd5mekAPq7EDiu76pxOkKpp6DTGmma7DF9x4vgaq5T9PCar1ndsQDUp60hgmvKvLrtkysquSY1jfQq9Q7dMM7OVVCzQSKhYT+ALEuZ3Pv0xeaC8F/ECokULHgVeMXMMrWx/bpYp13dYRMlhMEM6gXrPoVesZUlmtHSrSx5hjGs/GlButcRJWCVEAhZl5LFa59QQ1nhByNaEOw+M+MgSzLmaLc+NWPizPQQeRONorgL2PrqtNKQ0vU0QOx4HUr/6f5PJFYKGmckjOZoSKV3pg+naeRVX2rarFbzRJcGow2o7L0rtXGZYcu7axuRHdrw2szyyYS0ihuuZuCTaRk8KNirhSeQy1WrB3fe/GNn1iFE29mO9nFLvZAHi4WKmpcBgGtM9Kbg+LXy/oy3IUuWkT8MXWinAgwaJfj37WyNTchHoinhD9AMVbs7BL0oTMHtONV1CL/QCXrHKj7t4TzvrJR5i/UPqkDJR5RN7SmJHRUNQKLFTGPFWPbVaxpEQxoAa7BwKXELYZLrk4WzYS+ldA/G0FPWRUS1i91uCPeLO5JEqhBBtWo1Bwu0N57UJglIpSYGOJti6gqk9pRNP1rZMIsRqhViZOjs4FWSABpOa1qUwiyzp02LLCnHVOAvoZAXUdABjutIhCL3r8zthVvgb92TKggRk8HhhQt5ynQU40IU2Wv6c8booHOZDVLYKh/D6q7+0dId5x9Ls48JissF0P9YmvvcsTKNnkV8FpPNkknwlKkfD1ZI71MzLOHPz7fuQl5N6HzmWHfXTUVgg/HEku59qsaMaS70s++vDANpk2tHrOLhSDdbh96LzNSSi417WBBwvc9kXueBccsse0+ZnomTTIyr2KOr1kArFPck4xxj/o3EqdOQcarJ++7TGVQnlqrqAezew7cP1/mPMosSDH9YhddllApPFM9QKZXBTK8IkjzykHqBIa9RAanApleFcjwiiDNKwepPgFM9jOVA2R6VSDDK4I0rxyk+gQw7GeKA2R6VSDDK4I0rxyk+gE0gjLzIqXLx6JtFvi+kmsV+umYATOmttkrwyYWYjLbGCk2797//yPxWEZ8I3FCpG2mbe3U7+wfymNLtqQMDqlanZroOCuNwrKUKDNbhOSZHoJeerAtvrQOZL3BPxmW+T0lekJNcH0BoreDjAsmRNxAywec663+ew==";
const workerResultHash = "1c13a6df5be885374473b9eeef2775489155c7dba99ef646f1265a4707a6c5ba";
const reviewHash = "d".repeat(64);

function workerJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(workerJson).join(",")}]`;
  if (value !== null && typeof value === "object") {
    const item = value as Record<string, unknown>;
    return `{${Object.keys(item).sort()
      .map((key) => `${JSON.stringify(key)}:${workerJson(item[key])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}
function fixture(): LayerAssemblyVerificationInput {
  const f = JSON.parse(brotliDecompressSync(
    Buffer.from(workerFixtureBrotliBase64, "base64")).toString("utf8")) as any;
  return { objectId: f.objectId, inputManifestHash: f.inputManifestHash,
    sourceFiles: f.sources.map((source: any) => ({
      sourceFileId: source.sourceFileId, objectId: source.objectId,
      sha256: source.sha256, stages: source.stages,
      sourceReviewHash: reviewHash, sectionCode: source.sectionCode })),
    sourceReviews: Object.fromEntries(f.sources.map((source: any) => [source.sourceFileId,
      { sourceSha256: source.sha256, revisionStatus: source.revisionStatus,
        approvalStatus: source.approvalStatus, sectionCode: source.sectionCode,
        pageStages: source.pageStages, contentHash: reviewHash, decisionHash: reviewHash }])),
    textArtifacts: Object.fromEntries(f.textArtifacts.map((artifact: any) => [
      artifact.sourceFileId, { content_json: artifact,
        content_hash: sha256(canonicalJson(artifact)) }])),
    result: f.result };
}
function rehashResult(input: LayerAssemblyVerificationInput): void {
  const result = input.result as any;
  const { contentHash: _old, ...body } = result;
  result.contentHash = sha256(workerJson(body));
}

test("independently verifies Python layer assembly fixture with abstentions and caps", () => {
  const input = fixture();
  const result = input.result as any;
  assert.equal(result.contentHash, workerResultHash);
  assert.equal(verifyLayerAssemblyProposals(input), true);
  assert.deepEqual(result.codeRows.map((row: any) => [row.parameterCode, row.proposalCount,
    row.abstentionCount, row.ocrRequiredPageCount, row.truncatedProposalCount]),
  [["SPZU-032", 0, 0, 0, 0], ["AR-044", 26, 0, 1, 10], ["ZU-125", 1, 5, 1, 0]]);
  assert.equal(result.codeRows.every((row: any) => row.status === "ABSTAIN"
    && row.absenceConclusion === "NOT_AVAILABLE"), true);
  assert.equal(result.findingCount, null);
  assert.equal(result.parameterCoverage, null);
  assert.equal(result.codeRows[1].proposals.length, 16);
  assert.equal(result.codeRows[0].reasonCodes.includes("EXISTING_SITE_GP_TABLE_ROW_REVIEW"), true);
});

test("rejects rehashed forged locator, status, inferred value, and false-zero counters", () => {
  const changes: Array<(input: LayerAssemblyVerificationInput) => void> = [
    (input) => { (input.result as any).codeRows[2].proposals[0].roles.material.lineText = "fake"; },
    (input) => { (input.result as any).codeRows[1].proposals[0].roles.heading.bboxMilliPoints[0] += 1; },
    (input) => { (input.result as any).codeRows[2].proposals[0].rawThickness = "70 мм"; },
    (input) => { (input.result as any).codeRows[2].proposals[0].typeAssociationStatus = "VERIFIED"; },
    (input) => { (input.result as any).codeRows[1].status = "PASS"; },
    (input) => { (input.result as any).codeRows[1].ocrRequiredPageCount = 0; },
    (input) => { (input.result as any).codeRows[1].truncatedProposalCount = 0; },
    (input) => { (input.result as any).codeRows[2].abstentions = []; },
    (input) => { (input.result as any).codeRows[1].reasonCodes =
      (input.result as any).codeRows[1].reasonCodes.filter((r: string) => r !== "OVERSIZE_ANCHOR_LINE_DEFERRED"); },
    (input) => { (input.result as any).findingCount = 1; },
  ];
  for (const change of changes) {
    const input = fixture(); change(input); rehashResult(input);
    assert.equal(verifyLayerAssemblyProposals(input), false);
  }
});

test("rejects unapproved source, wrong stage or section, altered artifact, and cross-heading forgery", () => {
  const changes: Array<(input: LayerAssemblyVerificationInput) => void> = [
    (input) => { input.sourceReviews["F-AR"].approvalStatus = "UNAPPROVED"; },
    (input) => { input.sourceReviews["F-AR"].contentHash = "e".repeat(64); },
    (input) => { input.sourceFiles[1].stages = ["RD"]; },
    (input) => { input.sourceFiles[1].sectionCode = "OV"; },
    (input) => { input.textArtifacts["F-AR"].content_hash = "f".repeat(64); },
    (input) => { (input.textArtifacts["F-AR"].content_json as any).pages[3].quality.disposition = "TEXT_LAYER_CANDIDATE"; },
    (input) => { (input.result as any).codeRows[2].proposals[0].roles.type.lineText = "Тип 1"; },
    (input) => { input.inputManifestHash = "b".repeat(64); },
  ];
  for (const [index, change] of changes.entries()) {
    const input = fixture(); change(input);
    assert.equal(verifyLayerAssemblyProposals(input), false, `tamper ${index}`);
  }
});
